services:
  gateway:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.gateway
    deploy:
      replicas: 3
    environment:
      - PORT=3000
    networks:
      - api-network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
    networks:
      - api-network

networks:
  api-network:
