networks:
  api-gateway:
    driver: bridge

services:
  gateway:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile.gateway
    deploy:
      replicas: 3
    env_file:
      - .env
    environment:
      - PORT=3000
    networks:
      - api-gateway

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    depends_on:
      - gateway
    networks:
      - api-gateway
